In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [29]:
data.to_csv("acuracia.csv")

In [31]:
data = pd.read_csv('acuracia-T.csv', sep=',')
data

,Algoritmos,20newsGroup,Classic3,CSTR,Irish Economic Sentiment,Multi Domain Sentiment,NSF,Opinosis-Parsed,re8,Review Polarity,Reviews,SyskillWelbert-Parsed
0,NB,0.913116,0.959972,0.846154,0.681325,0.826750,0.838179,0.501007,0.938233,0.8135,0.941263,0.871257
1,KNN,0.807053,0.951233,0.869565,0.569880,0.736375,0.796180,0.607093,0.939145,0.6365,0.927501,0.892216
2,SVM,0.915415,0.974771,0.856187,0.687952,0.807750,0.825352,0.616695,0.974068,0.8605,0.964119,0.916168
3,Decision Tree,0.644246,0.850599,0.682274,0.510241,0.698125,0.624762,0.567136,0.916602,0.6475,0.898255,0.952096
4,Random Forest,0.840817,0.933615,0.769231,0.644578,0.823875,0.753516,0.607867,0.932760,0.7860,0.947161,0.919162
5,Convolutional 1D,0.968863,0.981149,0.769231,0.692169,0.755250,0.937530,0.980404,0.967504,0.6050,0.926321,0.844311
6,LSTM,0.950347,0.890310,0.750000,0.666265,0.574750,0.945838,0.980398,0.935920,0.5430,0.815434,0.750000

In [32]:
new_tab = pd.DataFrame()
new_tab['Colections'] = data["Algoritmos"]
new_tab['rank 20ng'] = data["20newsGroup"].rank() 
new_tab['rank Classic3'] = data["Classic3"].rank() 
new_tab['rank CSTR'] = data["CSTR"].rank()
new_tab['rank Irish Economic Sentiment'] = data["Irish Economic Sentiment"].rank() 
new_tab['rank Multi Domain Sentiment'] = data["Multi Domain Sentiment"].rank() 
new_tab['rank NSF'] = data["NSF"].rank() 
new_tab['rank Opinosis-Parsed'] = data["Opinosis-Parsed"].rank() 
new_tab['rank re8'] = data["re8"].rank()
new_tab['rank Review Polarity'] = data["Review Polarity"].rank()
new_tab['rank Reviews'] = data["Reviews"].rank()
new_tab['rank SyskillWelbert-Parsed'] = data["SyskillWelbert-Parsed"].rank()
new_tab

,Colections,rank 20ng,rank Classic3,rank CSTR,rank Irish Economic Sentiment,rank Multi Domain Sentiment,rank NSF,rank Opinosis-Parsed,rank re8,rank Review Polarity,rank Reviews,rank SyskillWelbert-Parsed
0,NB,4.0,5.0,5.0,5.0,7.0,5.0,1.0,4.0,6.0,5.0,3.0
1,KNN,2.0,4.0,7.0,2.0,3.0,3.0,3.0,5.0,3.0,4.0,4.0
2,SVM,5.0,6.0,6.0,6.0,5.0,4.0,5.0,7.0,7.0,7.0,5.0
3,Decision Tree,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,7.0
4,Random Forest,3.0,3.0,3.5,3.0,6.0,2.0,4.0,2.0,5.0,6.0,6.0
5,Convolutional 1D,7.0,7.0,3.5,7.0,4.0,6.0,7.0,6.0,2.0,3.0,2.0
6,LSTM,6.0,2.0,2.0,4.0,1.0,7.0,6.0,3.0,1.0,1.0,1.0

In [12]:
new_tab.mean()

rank NB                  6.0
rank KNN                 6.0
rank SVM                 6.0
rank Decision Tree       6.0
rank Random Forest       6.0
rank Convolutional 1D    6.0
rank LSTM                6.0
dtype: float64

In [17]:
data = pd.read_csv('NB.csv', sep=',')
data

,params,20newsGroup,Classic3,CSTR,Irish_Economic_Sentiment,Multi_Domain_Sentiment,NSF,Opinosis-Parsed,re8,Review_Polarity,Reviews,SyskillWelbert-Parsed
0,{'mnb__alpha': 1e-05},0.898179,0.950388,0.792642,0.680723,0.754500,0.795230,0.410872,0.915168,0.7555,0.907840,0.811377
1,{'mnb__alpha': 1e-06},0.893230,0.948414,0.782609,0.676506,0.748875,0.791334,0.402509,0.907610,0.7435,0.899730,0.799401
2,{'mnb__alpha': 0.001},0.906841,0.954475,0.819398,0.676506,0.775250,0.810243,0.444014,0.928329,0.7745,0.929467,0.829341
3,{'mnb__alpha': 0.01},0.913116,0.958421,0.842809,0.681325,0.788625,0.826112,0.483042,0.936669,0.7965,0.937823,0.853293
4,{'mnb__alpha': 0.1},0.905780,0.959972,0.846154,0.675301,0.809500,0.838179,0.501007,0.938233,0.8090,0.941263,0.871257
5,{'mnb__alpha': 1.0},0.857964,0.954757,0.698997,0.536747,0.826750,0.746294,0.332352,0.863565,0.8135,0.864094,0.742515

In [22]:
data = data.T
data

,0,1,2,3,4,5
params,{'mnb__alpha': 1e-05},{'mnb__alpha': 1e-06},{'mnb__alpha': 0.001},{'mnb__alpha': 0.01},{'mnb__alpha': 0.1},{'mnb__alpha': 1.0}
20newsGroup,0.898179,0.89323,0.906841,0.913116,0.90578,0.857964
Classic3,0.950388,0.948414,0.954475,0.958421,0.959972,0.954757
CSTR,0.792642,0.782609,0.819398,0.842809,0.846154,0.698997
Irish_Economic_Sentiment,0.680723,0.676506,0.676506,0.681325,0.675301,0.536747
Multi_Domain_Sentiment,0.7545,0.748875,0.77525,0.788625,0.8095,0.82675
NSF,0.79523,0.791334,0.810243,0.826112,0.838179,0.746294
Opinosis-Parsed,0.410872,0.402509,0.444014,0.483042,0.501007,0.332352
re8,0.915168,0.90761,0.928329,0.936669,0.938233,0.863565
Review_Polarity,0.7555,0.7435,0.7745,0.7965,0.809,0.8135
Reviews,0.90784,0.89973,0.929467,0.937823,0.941263,0.864094
SyskillWelbert-Parsed,0.811377,0.799401,0.829341,0.853293,0.871257,0.742515

In [24]:
data.to_csv("NB_T.csv")

In [26]:
data = pd.read_csv('NB_T.csv', sep=',')
data

,params,{'mnb__alpha': 1e-05},{'mnb__alpha': 1e-06},{'mnb__alpha': 0.001},{'mnb__alpha': 0.01},{'mnb__alpha': 0.1},{'mnb__alpha': 1.0}
0,20newsGroup,0.898179,0.893230,0.906841,0.913116,0.905780,0.857964
1,Classic3,0.950388,0.948414,0.954475,0.958421,0.959972,0.954757
2,CSTR,0.792642,0.782609,0.819398,0.842809,0.846154,0.698997
3,Irish_Economic_Sentiment,0.680723,0.676506,0.676506,0.681325,0.675301,0.536747
4,Multi_Domain_Sentiment,0.754500,0.748875,0.775250,0.788625,0.809500,0.826750
5,NSF,0.795230,0.791334,0.810243,0.826112,0.838179,0.746294
6,Opinosis-Parsed,0.410872,0.402509,0.444014,0.483042,0.501007,0.332352
7,re8,0.915168,0.907610,0.928329,0.936669,0.938233,0.863565
8,Review_Polarity,0.755500,0.743500,0.774500,0.796500,0.809000,0.813500
9,Reviews,0.907840,0.899730,0.929467,0.937823,0.941263,0.864094
10,SyskillWelbert-Parsed,0.811377,0.799401,0.829341,0.853293,0.871257,0.742515

In [27]:
data.mean()

{'mnb__alpha': 1e-05}    0.788402
{'mnb__alpha': 1e-06}    0.781247
{'mnb__alpha': 0.001}    0.804397
{'mnb__alpha': 0.01}     0.819794
{'mnb__alpha': 0.1}      0.826877
{'mnb__alpha': 1.0}      0.748867
dtype: float64

In [ ]:
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank() 
  
# display 
data

In [ ]:
data.to_csv("NB_rank.csv")

In [ ]:
data = pd.read_csv('knn.csv', sep=',')
data

In [ ]:
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank() 
  
# display 
data

In [ ]:
data.to_csv("knn_rank.csv")

In [ ]:
data = pd.read_csv('SVM.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
# display 
data 
data.to_csv("SVM_rank.csv")

In [ ]:
data

In [ ]:
data = pd.read_csv('decision_tree.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
data.to_csv("decision_tree-rank.csv")

In [ ]:
# display 
data

In [ ]:
data = pd.read_csv('random_forest.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
data.to_csv("random_forest-rank.csv")

In [ ]:
data