In [12]:
import pandas as pd 
import matplotlib.pyplot as plt

In [13]:
data = pd.read_csv('accuracy.csv', sep=';')

In [14]:
data

,Collections,NB,KNN,SVM,Decision Tree,Random Forest,Deep Learning
0,20newsGroup,0.913116,0.807053,0.915415,0.644246,0.840817,0.968863
1,Classic3,0.959972,0.951233,0.974771,0.850599,0.933615,0.981149
2,CSTR,0.846154,0.869565,0.856187,0.682274,0.769231,0.769231
3,Irish Economic Sentiment,0.681325,0.569880,0.687952,0.510241,0.644578,0.692169
4,Multi Domain Sentiment,0.826750,0.736375,0.807750,0.698125,0.823875,0.755250
5,NSF,0.838179,0.796180,0.825352,0.624762,0.753516,0.937530
6,Opinosis-Parsed,0.501007,0.607093,0.616695,0.567136,0.607867,0.980404
7,re8,0.938233,0.939145,0.974068,0.916602,0.932760,0.967504
8,Review Polarity,0.813500,0.636500,0.860500,0.647500,0.786000,0.605000
9,Reviews,0.941263,0.927501,0.964119,0.898255,0.947161,0.926321
10,SyskillWelbert-Parsed,0.871257,0.892216,0.916168,0.952096,0.919162,0.844311

In [15]:
data.mean()

NB               0.830069
KNN              0.793886
SVM              0.854452
Decision Tree    0.726531
Random Forest    0.814417
Deep Learning    0.857067
dtype: float64

In [16]:
#serve para transpor a tabela
#data = data.T
#data

In [17]:
data = pd.read_csv('NB.csv', sep=',')
data

,params,20newsGroup,Classic3,CSTR,Irish_Economic_Sentiment,Multi_Domain_Sentiment,NSF,Opinosis-Parsed,re8,Review_Polarity,Reviews,SyskillWelbert-Parsed
0,{'mnb__alpha': 1e-05},0.898179,0.950388,0.792642,0.680723,0.754500,0.795230,0.410872,0.915168,0.7555,0.907840,0.811377
1,{'mnb__alpha': 1e-06},0.893230,0.948414,0.782609,0.676506,0.748875,0.791334,0.402509,0.907610,0.7435,0.899730,0.799401
2,{'mnb__alpha': 0.001},0.906841,0.954475,0.819398,0.676506,0.775250,0.810243,0.444014,0.928329,0.7745,0.929467,0.829341
3,{'mnb__alpha': 0.01},0.913116,0.958421,0.842809,0.681325,0.788625,0.826112,0.483042,0.936669,0.7965,0.937823,0.853293
4,{'mnb__alpha': 0.1},0.905780,0.959972,0.846154,0.675301,0.809500,0.838179,0.501007,0.938233,0.8090,0.941263,0.871257
5,{'mnb__alpha': 1.0},0.857964,0.954757,0.698997,0.536747,0.826750,0.746294,0.332352,0.863565,0.8135,0.864094,0.742515

In [22]:
data = data.T
data

,0,1,2,3,4,5
params,{'mnb__alpha': 1e-05},{'mnb__alpha': 1e-06},{'mnb__alpha': 0.001},{'mnb__alpha': 0.01},{'mnb__alpha': 0.1},{'mnb__alpha': 1.0}
20newsGroup,0.898179,0.89323,0.906841,0.913116,0.90578,0.857964
Classic3,0.950388,0.948414,0.954475,0.958421,0.959972,0.954757
CSTR,0.792642,0.782609,0.819398,0.842809,0.846154,0.698997
Irish_Economic_Sentiment,0.680723,0.676506,0.676506,0.681325,0.675301,0.536747
Multi_Domain_Sentiment,0.7545,0.748875,0.77525,0.788625,0.8095,0.82675
NSF,0.79523,0.791334,0.810243,0.826112,0.838179,0.746294
Opinosis-Parsed,0.410872,0.402509,0.444014,0.483042,0.501007,0.332352
re8,0.915168,0.90761,0.928329,0.936669,0.938233,0.863565
Review_Polarity,0.7555,0.7435,0.7745,0.7965,0.809,0.8135
Reviews,0.90784,0.89973,0.929467,0.937823,0.941263,0.864094
SyskillWelbert-Parsed,0.811377,0.799401,0.829341,0.853293,0.871257,0.742515

In [24]:
data.to_csv("NB_T.csv")

In [26]:
data = pd.read_csv('NB_T.csv', sep=',')
data

,params,{'mnb__alpha': 1e-05},{'mnb__alpha': 1e-06},{'mnb__alpha': 0.001},{'mnb__alpha': 0.01},{'mnb__alpha': 0.1},{'mnb__alpha': 1.0}
0,20newsGroup,0.898179,0.893230,0.906841,0.913116,0.905780,0.857964
1,Classic3,0.950388,0.948414,0.954475,0.958421,0.959972,0.954757
2,CSTR,0.792642,0.782609,0.819398,0.842809,0.846154,0.698997
3,Irish_Economic_Sentiment,0.680723,0.676506,0.676506,0.681325,0.675301,0.536747
4,Multi_Domain_Sentiment,0.754500,0.748875,0.775250,0.788625,0.809500,0.826750
5,NSF,0.795230,0.791334,0.810243,0.826112,0.838179,0.746294
6,Opinosis-Parsed,0.410872,0.402509,0.444014,0.483042,0.501007,0.332352
7,re8,0.915168,0.907610,0.928329,0.936669,0.938233,0.863565
8,Review_Polarity,0.755500,0.743500,0.774500,0.796500,0.809000,0.813500
9,Reviews,0.907840,0.899730,0.929467,0.937823,0.941263,0.864094
10,SyskillWelbert-Parsed,0.811377,0.799401,0.829341,0.853293,0.871257,0.742515

In [27]:
data.mean()

{'mnb__alpha': 1e-05}    0.788402
{'mnb__alpha': 1e-06}    0.781247
{'mnb__alpha': 0.001}    0.804397
{'mnb__alpha': 0.01}     0.819794
{'mnb__alpha': 0.1}      0.826877
{'mnb__alpha': 1.0}      0.748867
dtype: float64

In [ ]:
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank() 
  
# display 
data

In [ ]:
data.to_csv("NB_rank.csv")

In [ ]:
data = pd.read_csv('knn.csv', sep=',')
data

In [ ]:
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank() 
  
# display 
data

In [ ]:
data.to_csv("knn_rank.csv")

In [ ]:
data = pd.read_csv('SVM.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
# display 
data 
data.to_csv("SVM_rank.csv")

In [ ]:
data

In [ ]:
data = pd.read_csv('decision_tree.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
data.to_csv("decision_tree-rank.csv")

In [ ]:
# display 
data

In [ ]:
data = pd.read_csv('random_forest.csv', sep=',')
# creating a rank column and passing the returned rank series 
data["Rank"] = data["params"].rank()  
data.to_csv("random_forest-rank.csv")

In [ ]:
data